### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by docen67** [MicrosoftDocs/xamarin-docs.es-es#16]
If i have 2 activities one for log-in and another for the welcome page and i want to set the toolbar in my second activity only ,how can i do?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 077a373a-710a-4514-ba04-dee36309d7b3
* Version Independent ID: f8357c4d-8711-457a-3577-cce29464b51e
* Content: [Reemplazar la barra de acciones - Xamarin](https://docs.microsoft.com/es-es/xamarin/android/user-interface/controls/tool-bar/replacing-the-action-bar#overview)
* Content Source: [docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @docen67, unfortunately we can't answer specific questions here; your best bet is to visit https://developercommunity.visualstudio.com/spaces/8/index.html to get help.

**Comment by CeciAc** [comment]
Hello, @docen67,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
