### ISSUE TITLE
inicios

### ISSUE THREAD

**Issue by Yadhira1234** [MicrosoftDocs/xamarin-docs.es-es#17]
Documentacion

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d8ef5687-ac87-e450-5d84-f17bc91788fe
* Version Independent ID: 1fd9e99d-1119-f1ff-a5d9-d8c58b5c47be
* Content: [Requisitos de Xamarin.Forms - Xamarin](https://docs.microsoft.com/es-es/xamarin/xamarin-forms/get-started/installation?tabs=vswin#universal-windows-platform-uwp)
* Content Source: [docs/xamarin-forms/get-started/installation.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/xamarin-forms/get-started/installation.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by LisandroSu** [comment]
Hola, @Yadhira1234 ,

Gracias por tus comentarios. Necesitamos más información para poder tratar este problema. ¿Puede proporcionar instrucciones más detalladas y líneas específicas que necesitan revisión / arreglo?
 
Saludos cordiales,
Equipo de Microsoft DOCS International

**Comment by CeciAc** [comment]
Hola, @Yadhira1234 ,
Gracias una vez más por tu comentario.
Lamentablemente, todavía nos falta información y no podemos procesar sus comentarios. Estamos cerrando este problema de GitHub en este momento, pero le recomendamos que envíe más comentarios en el futuro.

Saludos cordiales,
Equipo de Microsoft DOCS International
