### ISSUE TITLE
Permisos en android a partir de la versión 23

### ISSUE THREAD

**Issue by sergioacortes** [MicrosoftDocs/xamarin-docs.es-es#18]
A partir de la versión 23 se deben de especificar los permisos AccessCoarseLocation y AccessFineLocation en runtime, estaría bien que actualizaran la guía de ejemplo.

https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 732de335-2b07-a3f1-dad1-88bf6c77b80a
* Version Independent ID: a0979276-6fb0-fede-805b-ad7cc80a6d4d
* Content: [Mapa de Xamarin.Forms - Xamarin](https://docs.microsoft.com/es-es/xamarin/xamarin-forms/user-interface/map)
* Content Source: [docs/xamarin-forms/user-interface/map.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/xamarin-forms/user-interface/map.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by DavidPrio** [comment]
Hola, @sergioacortes : 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migramos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/xamarin-docs/issues/688. 
Apreciamos su contribución a nuestros artículos.  

Atentamente,

Equipo internacional de Microsoft Docs
