### ISSUE TITLE
Error en el código del documento

### ISSUE THREAD

**Issue by Luismi1601** [MicrosoftDocs/xamarin-docs.es-es#29]
Buenos días,

El código que se ha expuesto en este articulo para aprender a programar en xamarin tiene un error wn la parte de UWP, concretamente en la parte del código del final (async task<Phoneline>...) que hace que no se peuda seguir adelante con el curso.

Gracias,
Un saludo,
---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Inicio rápido de Xamarin.Forms - Xamarin](https://docs.microsoft.com/es-es/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #937](https://github.com/MicrosoftDocs/xamarin-docs/issues/937) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @Luismi1601 : 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/xamarin-docs/issues/937. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
