### ISSUE TITLE
Comentario

### ISSUE THREAD

**Issue by Moises1085** [MicrosoftDocs/xamarin-docs.es-es#33]
Vamos a probar el producto y ver que tal

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 56db63fe-87b2-548b-2064-c77ce96ef65a
* Version Independent ID: 0d6a93fb-72b0-4998-fb95-946e7ca2ff02
* Content: [Instalación y configuración de Xamarin.Android - Xamarin](https://docs.microsoft.com/es-es/xamarin/android/get-started/installation/index)
* Content Source: [docs/android/get-started/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/android/get-started/installation/index.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by LisandroSu** [comment]
Hola, @Moises1085 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
