### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by jfranpino** [MicrosoftDocs/xamarin-docs.es-es#34]
He intentado varias veces hacerlo y no funciona, resulta con múltiples errores.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: bfbead94-9441-acc3-8559-6d09713f5274
* Version Independent ID: 15fb3cb2-7408-ba72-4795-c7889caeb8da
* Content: [Tutorial: uso de notificaciones locales en Xamarin.Android - Xamarin](https://docs.microsoft.com/es-es/xamarin/android/app-fundamentals/notifications/local-notifications-walkthrough)
* Content Source: [docs/android/app-fundamentals/notifications/local-notifications-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/android/app-fundamentals/notifications/local-notifications-walkthrough.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Hola, @jfranpino 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by jfranpino** [comment]
Gracias por la respuesta. referente a esta documentación, en el método:
void CreateNotificationChannel() 
y en la linea
var name = Resources.GetString(Resource.String.channel_name);

No debería ser:
var name = Resources.GetString(Resource.Strings.channel_name);

Creo que hay un error de un caracter o no es así?

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1227](https://github.com/MicrosoftDocs/xamarin-docs/issues/1227) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @jfranpino 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/xamarin-docs/issues/1227. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
