### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by cristalgarza** [MicrosoftDocs/xamarin-docs.es-es#76]
Tengo dudas por qué en el visual studio de documentación sale la instalación del “xamarin.from o nativa” y en el mío solo sale “xamarin.from”... me dicen que puede ser las actualizaciones pero nomas no me sale...

Otra cosa también en donde sale en la pestaña de “ayuda” después “xamarin” de desplaza una lista y a mi solo me salen 3 opciones que son:
- open logs
- zip logs 
- zip logs ( Last 7 days)
Y sale que viene abajo otras 3 cosas más y esas no las tengo que son las siguientes 
- xamarin android release notes 
- xamarin ios release notes
- xamarin visual studio release notes 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: fc8e7fd2-9fb4-7893-f0e0-e3883df3e01f
* Version Independent ID: b9fe6738-cf6d-8e3e-b2bb-0d6094ca4bc2
* Content: [Instalación de Xamarin en Visual Studio de 2019 - Xamarin](https://docs.microsoft.com/es-es/xamarin/get-started/installation/windows?utm_source=t.co&utm_medium=referral#feedback)
* Content Source: [docs/get-started/installation/windows.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/get-started/installation/windows.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun

**Comment by CeciAc** [comment]
Hola, @cristalgarza 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
