### ISSUE TITLE
Aprovisionamiento automático con Notificaciones push 

### ISSUE THREAD

**Issue by dertin** [MicrosoftDocs/xamarin-docs.es-es#77]
No se crea un aprovisionamiento automático de forma explícita (en lugar de un comodín) si se activa en Entitlements.plist el permiso Notificaciones push. ¿ Esto es normal ? No queda claro en la documentación.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5ccadd93-fcc8-6a15-9670-d5af7ee7f6f8
* Version Independent ID: 188007d3-cf20-97ba-137f-64ff25a88e7c
* Content: [Aprovisionamiento automático para Xamarin.iOS - Xamarin](https://docs.microsoft.com/es-es/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=macos#feedback)
* Content Source: [docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by CeciAc** [comment]
Hola, @dertin 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
