### ISSUE TITLE
Aplicación Traductora

### ISSUE THREAD

**Issue by carlosluna1978** [MicrosoftDocs/xamarin-docs.es-es#79]
Buenas tardes he buscado en la documentación de xamarin pero no encuentro un ejemplo de como crear una aplicacion traductora sin necesidad de utilizar bibliotecas traductores como la de google por ejemplo Duolingo tal vez me podrían ayudar al respecto muchas gracias. 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Navegación en una aplicación de varias páginas de Xamarin.Forms - Xamarin](https://docs.microsoft.com/es-mx/xamarin/get-started/quickstarts/multi-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hola, @carlosluna1978 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
