### ISSUE TITLE
Error en el menu en la app UWP

### ISSUE THREAD

**Issue by wjvelasquez** [MicrosoftDocs/xamarin-docs.es-es#82]
La app funciona como se espera, aunque tiene algunos errores.
El problema es que en la app UWP, que no entiendo la razón de obviarla por parte de ustedes, el menú no se ve bien. El menú no muestra el texto a menos que se le de expandir en los 3 puntos.

En mi opinión. Creo que deberían ponerle mas empeño a UWP y no dejarla por fuera en sus ejemplos.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Navegación en una aplicación de varias páginas de Xamarin.Forms - Xamarin](https://docs.microsoft.com/es-es/xamarin/get-started/quickstarts/multi-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs.es-es/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @wjvelasquez
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hola, @wjvelasquez:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/xamarin-docs/issues/2391.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
