### ISSUE TITLE
Crea el diseño

### ISSUE THREAD

**Issue by patypo** [MicrosoftDocs/xamarin-docs.es-es#85]
Buen día, cuando voy a arrastrar el comando text(large) no me deja pegarlo en la plantilla android. Me podrían ayudar por favor y gracias.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Inicio rápido - Xamarin](https://docs.microsoft.com/es-es/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows#feedback)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.es-es/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by patypo** [comment]
Ya lo arregle, habia hecho el paso de "sugerencia" pero no debia hacerlo porque mi version de Visual Studio no es la mas reciente. Gracias

**Comment by srvbpigh** [comment]
Hello, @patypo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @patypo 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas.

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia.

Atentamente,

Equipo internacional de Microsoft Docs
